# BeautyIQ Revenue System
name = "BeautyIQ"
client_id = "2e14090ef13ee27f9547bdb4b77dc8a3"
application_url = "https://www.beautyiqapp.com"

[auth]
redirect_urls = [
  "https://www.beautyiqapp.com/auth/callback"
]

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_script_tags,write_script_tags"

[webhooks]
api_version = "2024-10"
